### ISSUE TITLE
How to set the height of modal, just like the width?

### ISSUE THREAD

**Issue by Symbolk** [visma-meglerfront/sweet-modal-vue#85]
I want to wrap a component in the modal, which requires the height to be set to 50%, but I cannot find how to do it like setting the width.

BTW, one advice: the usage should also be present following the installation in README, not util I checked the end of the demo page did I realized how to use it.

**Comment by eduardofinotti** [comment]
> 

Use inside  div of modal:

  **display: flex;  
  flex-wrap: wrap;**
